Hide robots setting if file does not exist.
quantcdn/drupal pull request #233
Opened 2024-03-03 02:31 UTC by kepol

See Drupal.org issue:

https://www.drupal.org/project/quantcdn/issues/3416118

2025-01-28 23:26 UTC, steveworley requested changes

2025-01-28 23:26 UTC, steveworley commented on quant.admin.inc
> +  $file = $_SERVER['DOCUMENT_ROOT'] . '/robots.txt';
I don't think we can do this, how does this work if the site is using a dynamically generated robots.txt file? For example using robotstxt module this doesn't create the file and just configures a route in PHP.

2025-01-28 23:27 UTC, steveworley commented on quant.admin.inc
> +  $file = $_SERVER['DOCUMENT_ROOT'] . '/robots.txt';
It probably needs to be a HTTP request to `/robots.txt` to see if the site is responding with it.

2025-01-29 01:28 UTC, kepol commented on quant.admin.inc
> +  $file = $_SERVER['DOCUMENT_ROOT'] . '/robots.txt';
@steveworley good catch! updated :)

2025-01-29 04:17 UTC, kepol commented
Given this is nearly the same as what is used in quant_api.module and I've tested locally and it works, I'm going to merge this.

```
...
  $file_get = drupal_http_request($url, $options);
  if ($file_get->code == 200) { 
...
```

2025-01-29 04:18 UTC, merged